### ISSUE TITLE
Error when getting data back from firebase

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/ProMa#100]
At the moment we run into an error, where the ProMa Checklist Data data sets in state "6" are not fetched back into the system.

Code has been  applied to stop the Schedule Job Type to fail and have a Error Log instead: https://github.com/phamos-eu/ProMa/pull/98

In the Error Log we now get

```
Traceback (most recent call last):
  File "apps/proma/proma/proma/doctype/proma_checklist_data/proma_checklist_data.py", line 203, in get_firebase
    storage.child(str(ref)).download(get_files_path(str(path)))
  File "env/lib/python3.7/site-packages/pyrebase/pyrebase.py", line 419, in download
    blob.download_to_filename(filename)
AttributeError: 'NoneType' object has no attribute 'download_to_filename'
```

There has been a number of entries where this fails. Unfortunatelly we can not track on which the errors are triggered and what the cause is.

**Comment by njoguchris** [comment]
What is the error given in the Error Log

**Comment by roquegv** [comment]
> What is the error given in the Error Log

Hi Chris, the error given in the Error Log is the one described in the issue's description. In the Error Log there is a title and there is a description. The description is the stated in this issue and the title was `'NoneType' object has no attribute 'download_to_filename'` if I remember well.

**Comment by wojosc** [comment]
@njoguchris @roquegv this error has returned! Not sure if we might have messed something up, when merging new code or if there is a "new" reason for the Schedule Job Type to run into this error.

I have a hint though, over which I cam accross lately:

What happens, when two images are uploaded that carry the same file_name.jpeg? How does the system react?

**Comment by roquegv** [comment]
I tried to get the same image twice to reproduce a possible error of files with the same names. I does not have any problem doing so. Here is how I checked:
```
In [4]: get_firebase("5nOV2YdDInm5WhP8rIgk/photos/23_1681281255430_JPEG_20230412_083402_2110525615297225531.jpg", "JPEG_20230412_083402_2110525615297225531.jpg")
Out[4]: '/files/JPEG_20230412_083402_2110525615297225531.jpg'

In [5]: get_firebase("5nOV2YdDInm5WhP8rIgk/photos/23_1681281255430_JPEG_20230412_083402_2110525615297225531.jpg", "JPEG_20230412_083402_2110525615297225531.jpg")
Out[5]: '/files/JPEG_20230412_083402_2110525615297225531.jpg'
```
That is basically downloading the image twice. The operation is successful.
