### ISSUE TITLE
Error on migrate

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/ProMa#106]
when trying to update a system on frappecloud we get an error on "bench migrate"

```
Migrating sonnen-final.frappe.cloud
Updating DocTypes for frappe	    : [========================================] 100%
Updating DocTypes for erpnext	    : [========================================] 100%
Updating DocTypes for suncycle	    : [========================================] 100%
Updating DocTypes for sonnen_api    : [========================================] 100%
Updating DocTypes for proma	    : [==============================	       ] 77%
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 243, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1205, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/frappe/frappe-bench/apps/proma/proma/proma/doctype/proma_checklist_data/proma_checklist_data.py", line 15, in <module>
    import pyrebase
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pyrebase/__init__.py", line 1, in <module>
    from .pyrebase import initialize_app
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/pyrebase/pyrebase.py", line 20, in <module>
    from requests_toolbelt.adapters import appengine
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/requests_toolbelt/adapters/appengine.py", line 42, in <module>
    from .._compat import gaecontrib
ImportError: cannot import name 'gaecontrib' from 'requests_toolbelt._compat' (/home/frappe/frappe-bench/env/lib/python3.7/site-packages/requests_toolbelt/_compat.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 31, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 433, in migrate
    migrate(context.verbose, skip_failing=skip_failing, skip_search_index=skip_search_index)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 72, in migrate
    frappe.model.sync.sync_all(verbose=verbose)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/sync.py", line 21, in sync_all
    sync_for(app, force, verbose=verbose, reset_permissions=reset_permissions)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/sync.py", line 74, in sync_for
    doc_path, force=force, ignore_version=True, reset_permissions=reset_permissions
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 153, in import_file_by_path
    path=path,
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 275, in import_doc
    doc.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 293, in insert
    self.run_post_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1087, in run_post_save_methods
    self.run_method("on_update")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 943, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 940, in fn
    return method_object(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 376, in on_update
    self.run_module_method("on_doctype_update")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 435, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 246, in load_doctype_module
    "Module import failed for {0} ({1})".format(doctype, module_name + " Error: " + str(e))
ImportError: Module import failed for Proma Checklist Data (proma.proma.doctype.proma_checklist_data.proma_checklist_data Error: cannot import name 'gaecontrib' from 'requests_toolbelt._compat' (/home/frappe/frappe-bench/env/lib/python3.7/site-packages/requests_toolbelt/_compat.py))
```

**Comment by roquegv** [comment]
This has something to do with `pyrebase` lib.

We can try to use `pyrebase4` instead of `pyrebase` also in the test system, not just in production.

There is a open PR that includes this change: https://github.com/phamos-eu/ProMa/pull/94. So, I would suggest to merge this PR and try `bench migrate` again. If this is a too big PR because it includes a lot of commits, then I can create another temporal branch to include just this change. Let me know what do you thing is better.
