### ISSUE TITLE
User not set when assigning via "Service Partner Bestellungen"

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/ProMa#107]
We had some permission issue when assigning checklists via the report view "Service Partner Bestellungen"

I could identify, that ProMa Checklist and ProMa Checklist Data had no Users assigned

the corresponding Purchase Order had no value set in the following field
![grafik](https://user-images.githubusercontent.com/22279621/235660499-1a4fba63-003d-40cd-9f18-3e0eef10efe4.png)

I will test if this might have something todo with permissions...

**Comment by wojosc** [comment]
when Purchase Order is not submitted we get an error:

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1473, in call
    return fn(*args, **newargs)
  File "apps/proma/proma/proma/report/service_partner_bestellungen/service_partner_bestellungen.py", line 169, in update_po_and_create_pc
    update_po(po, scheduled_date, users)
  File "apps/proma/proma/proma/report/service_partner_bestellungen/service_partner_bestellungen.py", line 193, in update_po
    po.save()
  File "apps/frappe/frappe/model/document.py", line 312, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 349, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1054, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 943, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 940, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/buying/doctype/purchase_order/purchase_order.py", line 57, in validate
    super(PurchaseOrder, self).validate()
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 33, in validate
    super(BuyingController, self).validate()
  File "apps/erpnext/erpnext/controllers/stock_controller.py", line 42, in validate
    super(StockController, self).validate()
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 145, in validate
    self.set_missing_values(for_validate=True)
  File "apps/erpnext/erpnext/controllers/buying_controller.py", line 82, in set_missing_values
    get_party_details(
  File "apps/erpnext/erpnext/accounts/party.py", line 64, in get_party_details
    return _get_party_details(
  File "apps/erpnext/erpnext/accounts/party.py", line 109, in _get_party_details
    frappe.throw(_("Not permitted for {0}").format(party), frappe.PermissionError)
  File "apps/frappe/frappe/__init__.py", line 504, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 434, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.PermissionError: Not permitted for phamos GmbH
```

This can be worked around when Purchase Order is submitted!

**Comment by wojosc** [comment]
tested. Is fixed.
