### ISSUE TITLE
Issue when installing

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/ProMa#69]
it seems we have a dependeny to suncycle/suncycle when installing the ProMa App:

```
Installing proma...
Updating DocTypes for proma	    : [========================================] 100%
Updating customizations for Purchase Order
An error occurred while installing proma: Purchase Order: Options must be a valid DocType for field Project Address in row 49
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 293, in install_app
    _install_app(app, verbose=context.verbose)
  File "apps/frappe/frappe/installer.py", line 200, in install_app
    sync_customizations(name)
  File "apps/frappe/frappe/modules/utils.py", line 112, in sync_customizations
    sync_customizations_for_doctype(data, folder)
  File "apps/frappe/frappe/modules/utils.py", line 171, in sync_customizations_for_doctype
    validate_fields_for_doctype(doctype)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 907, in validate_fields_for_doctype
    validate_fields(meta)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1314, in validate_fields
    check_link_table_options(meta.get("name"), d)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 986, in check_link_table_options
    WrongOptionsDoctypeLinkError,
  File "apps/frappe/frappe/__init__.py", line 511, in throw
    as_list=as_list,
  File "apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 434, in _raise_exception
    raise raise_exception(msg)
frappe.core.doctype.doctype.doctype.WrongOptionsDoctypeLinkError: Purchase Order: Options must be a valid DocType for field Project Address in row 49
```

**Comment by roquegv** [comment]
I'll take a look.

**Comment by roquegv** [comment]
Yes we have a dependency problem: the customizations for Purchase Order were exported to the ProMa app, but should be to the Suncycle app.
Will create a PR for this.

**Comment by roquegv** [comment]
This PR should solve the dependency problem https://github.com/phamos-eu/ProMa/pull/70
