### ISSUE TITLE
Issue when installing #2

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/ProMa#71]
Migrating sonnen-final.frappe.cloud
Updating DocTypes for frappe	    : [========================================] 100%
Updating DocTypes for erpnext	    : [========================================] 100%
Updating DocTypes for suncycle	    : [========================================] 100%
Updating DocTypes for sonnen_api    : [========================================] 100%
Updating Dashboard for frappe
Updating Dashboard for erpnext
Updating Dashboard for suncycle
Updating Dashboard for sonnen_api
Updating customizations for Address
Updating customizations for Contact
Updating customizations for Sales Order
Updating customizations for Purchase Order

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 31, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 433, in migrate
    migrate(context.verbose, skip_failing=skip_failing, skip_search_index=skip_search_index)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 77, in migrate
    sync_customizations()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 112, in sync_customizations
    sync_customizations_for_doctype(data, folder)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 171, in sync_customizations_for_doctype
    validate_fields_for_doctype(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 907, in validate_fields_for_doctype
    validate_fields(meta)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1308, in validate_fields
    check_table_multiselect_option(d)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1227, in check_table_multiselect_option
    meta = frappe.get_meta(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1111, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 49, in get_meta
    meta = Meta(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 106, in __init__
    super(Meta, self).__init__("DocType", doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 118, in __init__
    self.load_from_db()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/meta.py", line 111, in load_from_db
    super(Meta, self).load_from_db()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 164, in load_from_db
    _("{0} {1} not found").format(_(self.doctype), self.name), frappe.DoesNotExistError
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 511, in throw
    as_list=as_list,
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 434, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.DoesNotExistError: DocType ProMa Assigned User IDs not found

**Comment by wojosc** [comment]
after manually creating the doctype we get:

Migrating sonnen-final.frappe.cloud
Updating DocTypes for frappe	    : [========================================] 100%
Updating DocTypes for erpnext	    : [========================================] 100%
Updating DocTypes for suncycle	    : [========================================] 100%
Updating DocTypes for sonnen_api    : [========================================] 100%
Updating Dashboard for frappe
Updating Dashboard for erpnext
Updating Dashboard for suncycle
Updating Dashboard for sonnen_api
Updating customizations for Address
Updating customizations for Contact
Updating customizations for Sales Order
Updating customizations for Purchase Order

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 31, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 433, in migrate
    migrate(context.verbose, skip_failing=skip_failing, skip_search_index=skip_search_index)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/migrate.py", line 77, in migrate
    sync_customizations()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 112, in sync_customizations
    sync_customizations_for_doctype(data, folder)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/modules/utils.py", line 171, in sync_customizations_for_doctype
    validate_fields_for_doctype(doctype)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 907, in validate_fields_for_doctype
    validate_fields(meta)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1308, in validate_fields
    check_table_multiselect_option(d)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1235, in check_table_multiselect_option
    frappe.ValidationError,
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 511, in throw
    as_list=as_list,
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 479, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 434, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: DocType <b>ProMa Assigned User IDs</b> provided for the field <b>assigned_users_ids</b> must have atleast one Link field

**Comment by wojosc** [comment]
after adding this to that new DocType it ran smoothly:

![grafik](https://user-images.githubusercontent.com/22279621/228467492-5529985d-f35b-4756-9b2f-e00cd4a0d4cf.png)
