### ISSUE TITLE
error when submitting new checklist

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/ProMa#82]
Hi 
[Christopher Njogu](https://matrix.to/#/@njoguchris:matrix.org)
 we have a case that we have not really concidered at the moment. The customer will want to create ProMa Checkliste Templates and test them before going into production with them. Basically they will create ProMa Checklist Templates and play around with these for a while up until they submit them for production.
Playing around means, that they will have a Template in status "Draft" but already be sending it manually to the mobile app. In the mobile app they will take a look if everything works (Translations, hints, buttons ...item stuff). In this process they will want't to quickly remove the checklist again and recreate it with slightly different settings. Test again -> delete again etc.

This means, we are looking at once again manually creating checklists.

We are trying to create checklists manually at the moment, get an error though:
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

this is the checklist that we are using: https://sonnen-final.frappe.cloud/app/proma-checklist/PCT0022CL02926

My questions for now:

Why does the error come up and how do I solve it (can we set a understanable message for the next time)
Are we able to implement the option to send a checklist without it (or the template) being submitted?
Wolfram Schmidt
Wolfram Schmidt
Why does the error come up and how do I solve it (can we set a understanable message for the next time)
it seems to be connected to the Items "Extension" as soon as I delete these I am able to create the checklist -> Save it -> Submit it

Here is the error

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1473, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.submit()
  File "apps/frappe/frappe/model/document.py", line 1020, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1009, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 312, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 366, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1090, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 943, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 940, in fn
    return method_object(*args, **kwargs)
  File "apps/proma/proma/proma/doctype/proma_checklist/proma_checklist.py", line 19, in on_submit
    res = proma_checklist(self.name)
  File "apps/proma/proma/auto_custom.py", line 225, in proma_checklist
    b.hint if b.item_type == "Item" else None
  File "apps/proma/proma/auto_custom.py", line 204, in get_extensions_items
    idx, idx2, item_type, item_name, str(grp_id), hint)
  File "apps/proma/proma/auto_custom.py", line 138, in get_extension_items
    pi.append(get_item_values(json.loads(b.proma_item_template_values),
  File "/usr/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```

**Comment by njoguchris** [comment]
Yes was resolved by #84
